version: '3'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data
    command: [postgres, -c, 'listen_addresses=*', -c, log_statement=all]
    healthcheck:
      test: [CMD-SHELL, pg_isready -q -U postgres]
      interval: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
  express-app:
    build:
      context: ../..
      dockerfile: apps/server/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8000:8000'
    environment:
      APPNAME: ${APPNAME}
      PORT: ${PORT}
      NODE_ENV: prod
      LOCALE: true
      PRODUCTION_URL: ${PRODUCTION_URL}
      SECRET: ${SECRET}
      CLIENT_BASE_URL: ${CLIENT_BASE_URL}
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:${DATABASE_PORT}/${DATABASE_NAME}
    command: sh -c "npm run migrate:prod && npm run start"
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 2048M
