name: client-cd

on:
  pull_request:
    types: [opened, synchronize, closed]
  workflow_dispatch:

jobs:
  build:
    if: github.event.pull_request.merged == true && github.event.action == 'closed'
    name: Build and Push Docker Image
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Client Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.CLIENT_REPOSITORY_NAME }}:latest
          build-args: |
            BASE_API_URL=${{ secrets.BASE_API_URL }}

  deploy:
    if: github.event.pull_request.merged == true && github.event.action == 'closed'
    name: Deploy using Docker
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} > ~/.ssh/known_hosts

      - name: Deploy Docker Container
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          BASE_API_URL: ${{ secrets.BASE_API_URL }}
          CLIENT_REPOSITORY_NAME: ${{ secrets.CLIENT_REPOSITORY_NAME }}
          CLIENT_PORT: ${{ secrets.CLIENT_PORT }}
          CLIENT_CONTAINER_NAME: ${{ secrets.CLIENT_CONTAINER_NAME }}
        run: |
          ssh -T ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << EOF

          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

          docker container rm -f $CLIENT_CONTAINER_NAME || true

          docker system prune -a -f

          docker pull $DOCKER_USERNAME/$CLIENT_REPOSITORY_NAME:latest

          docker run -d --restart unless-stopped -p ${CLIENT_PORT}:80 --name $CLIENT_CONTAINER_NAME -e BASE_API_URL=$BASE_API_URL $DOCKER_USERNAME/$CLIENT_REPOSITORY_NAME:latest

          EOF